apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myfirstgoapp
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: myfirstgoapp
  spec:
   containers:
   - name: myapp
     image: adisai123/myfirstgo:latest
     ports:
     - containerPort: 8080
     volumeMounts:
     - name: credvolume
       mountPath: /etc/creds
       readOnly: true
   volumes:
   - name: credvolume
     secret:
      secretName: db-sercet
   nodeSelector:
    environment: dev