apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myfirstgoapp1
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: myfirstgoapp1
  spec:
   containers:
   - name: myapp1
     image: adisai123/myfirstgo:latest
     ports:
     - name: mygoport
       containerPort: 8080
     env:
     - name: SECRET_USERNAME
       valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
   nodeSelector:
    environment: dev