apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myinginx-rules
spec:
  rules:
  - host: hello1.com
    http:
      paths:
      - path: /
      backend:
        serviceName:  helloworld-v1
        servicePort:  80
  - host: hello2.com
    http:
      paths:
      - path: /
      backend:
        serviceName:  helloworld-v2
        servicePort:  80    