apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myfirstgoapp
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: myfirstgoapp
  spec:
   containers:
   - name: myapp
     image: adisai123/myfirstgo:2
     ports:
     - name: mygoport
       containerPort: 8080
   nodeSelector:
    environment: dev
 