apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gobgp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gobgp
    spec:
      containers:
        - name: gobgp
          image: pierky/gobgp
          ports:
            - name: mygoport
              containerPort: 179
---
apiVersion: v1
kind: Service
metadata:
  name: gobgp
spec:
  ports:
    - port: 179
      nodePort: 30000
      protocol: TCP
  selector:
    app: mygoport
  type: NodePort
