apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myfirstgoapp
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: myfirstgoapp
  spec:
   containers:
   - name: myfirstgoapp
     image: adisai123/daemonset:1
     ports:
     - name: mygoport
       containerPort: 8080
     resources:
      requests:
        cpu: 200m
 