apiVersion: v1
kind: Pod
metadata:
 name: myfirstgoapp
 labels:
  app: myfirstgo
spec:
 containers:
 - name: myfirstgocontiners
   image: adisai123/myfirstgo:03ced5393f70
   ports: 
   - containerPort: 8080