apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: newautscale
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myfirstgoapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50