apiVersion: v1
kind: Service
metadata:
 name: myfirstgo-service
spec:
 ports:
 - port: 31001
   nodePort: 31001
   targetPort: mygoport
   protocol: TCP
 selector:
  app: myfirstgoapp
 type: NodePort  